### ISSUE TITLE
Left side menu doesn't increase page size

### ISSUE THREAD

**Issue by ghost** [ContainerSSH/containerssh.github.io#10]
Some pages don't properly render the left side menu on smaller screens, e.g. https://containerssh.io/reference/backends/

**Comment by ecrazor1911** [comment]
It looks like a shape rendering issue. This CSS fix that, but the next bug is the icon hover issue.

```css
.md-icon svg {
    /* [...] */
    shape-rendering: crispedges;
}
```

![ektJuPchyj](https://user-images.githubusercontent.com/7604637/111043131-37de7a80-8441-11eb-8b5c-82cf6648ad66.gif)

**Comment by ecrazor1911** [comment]
A possible solution is adding `min-height` to `.md-main` CSS class, like this:

```css
.md-main {
    /* [...] */
    min-height: 75vh;
}
```
