### ISSUE TITLE
Kubernetes installation: readOnlyRootFilesystem not working at pod level, only at container level

### ISSUE THREAD

**Issue by jjournet** [ContainerSSH/containerssh.github.io#35]
## What would you like to add/change in the documentation?

While going through the installation for Kubernetes in docs/reference/installation.md, I  got an error when trying to deploy the deployment as described in the page.

I got the following error:
```
error: error validating "containerssh.yaml": error validating data: ValidationError(Deployment.spec.template.spec.securityContext): unknown field "readOnlyRootFilesystem" in io.k8s.api.core.v1.PodSecurityContext; if you choose to ignore these errors, turn validation off with --validate=false
```
I tried to move the the `readOnlyRootFilesystem` attribute at pod level:
```
---
# Deploy ContainerSSH with the service account and configmap applied.
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: containerssh
  name: containerssh
  namespace: containerssh
spec:
  replicas: 1
  selector:
    matchLabels:
      app: containerssh
  template:
    metadata:
      labels:
        app: containerssh
    spec:
      automountServiceAccountToken: true
      securityContext:
        runAsNonRoot: true
      containers:
      - image: containerssh/containerssh:0.4.1
        imagePullPolicy: IfNotPresent
        name: containerssh
        ports:
        - containerPort: 2222
          protocol: TCP
        volumeMounts:
        - mountPath: /etc/containerssh/host.key
          name: hostkey
          readOnly: true
          subPath: host.key
        - mountPath: /etc/containerssh/config.yaml
          name: config
          readOnly: true
          subPath: config.yaml
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
        securityContext:
          readOnlyRootFilesystem: true
      restartPolicy: Always
      serviceAccount: containerssh
      serviceAccountName: containerssh
      volumes:
      - name: hostkey
        secret:
          secretName: containerssh-hostkey
      - configMap:
          name: containerssh-config
        name: config
```
and it works.

so, I don't know if it's an API change or something. I checked the [doc about pod security context](https://kubernetes.io/docs/reference/kubernetes-api/workload-resources/pod-v1/#security-context)  and it wasn't clear if `readOnlyRootFilesystem` was limited to container.

I'm running Kubernetes 1.24.3, both clients and cluster.

I will deploy (at least for my dev phase) with that, until I come up with my own pods definition
Could be worse investigating. But as is, the doc doesn't work on 1.24.3
